In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

In [3]:
dataset = pd.read_csv(r"C:\Users\amita\Desktop\Deep Learning\ANN\P16-Artificial-Neural-Networks\Part 1 - Artificial Neural Networks\Churn_Modelling.csv")

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
X = dataset.iloc[:, 3:-1].values   #all rows, 4th col to last but one col
y = dataset.iloc[:, -1].values     #all rows, last col

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [10]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
ann = tf.keras.models.Sequential()  #helps to build a ann based on sequence of layers

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#units are the number of neurons in the hidden layer only one hidden layer
#first hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#second hidden layer

In [19]:
# model = keras.Sequential([
# keras.layers.Dense(3, input_shape = (5,),activation = 'relu'),
# keras.layers.Dense(2, input_shape = (3,),activation = 'relu'),
# keras.layers.Dense(1,activation = 'sigmoid'), this is output
# ]) can be done like this as well

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
#this is the output node so only one neuron is required as the output has 0 and 1 class so only 1 neuron is enough and the final activation function needs to be sigmoid activation function, sigmoid not only gives prediction but also the probability that the customer leaves the bank

In [21]:
ann.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])
# adam allows us to perform stochastic gradinet descend, non binary its categorical_crossentropy and for binary its the above one and for non binary the activation should be softmax

In [22]:
ann.fit(X_train,y_train, batch_size=32, epochs=100)
#epoch is to train it number of times to improve accuracy by back propagating

Epoch 1/100


250/250 [==============================] - 2s 1ms/step - loss: 0.5688 - accuracy: 0.7689
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4706 - accuracy: 0.7983
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4426 - accuracy: 0.8065
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4314 - accuracy: 0.8115
Epoch 5/100
250/250 [==============================] - 0s 989us/step - loss: 0.4256 - accuracy: 0.8135
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4218 - accuracy: 0.8167
Epoch 7/100
250/250 [==============================] - 0s 978us/step - loss: 0.4188 - accuracy: 0.8210
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4164 - accuracy: 0.8223
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4139 - accuracy: 0.8225
Epoch 10/100
250/250 [==============================] - 0s 1000us/step - loss: 0.4119

250/250 [==============================] - 0s 999us/step - loss: 0.3338 - accuracy: 0.8645
Epoch 77/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3332 - accuracy: 0.8629
Epoch 78/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3335 - accuracy: 0.8621
Epoch 79/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8627
Epoch 80/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.8643
Epoch 81/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.8635
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.8622
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3329 - accuracy: 0.8636
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8641
Epoch 85/100
250/250 [==============================] - 0s 997us/step - loss: 0.3327 - accura

In [23]:
ann.evaluate(X_test,y_test)

63/63 [==============================] - 0s 933us/step - loss: 0.3376 - accuracy: 0.8570


[0.3376462757587433, 0.8569999933242798]

In [24]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 76ms/step
[[False]]


In [25]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 807us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [26]:
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1498   97]
 [ 189  216]]


0.857

In [30]:
#1498 correct that customer stays
#216 correct that customer leaves 
#97 incoorect that customer levaes
#189 incorrrect that customer stays